spring:
  application:
    name: scaff-oauth2-server    # 项目名称尽量用小写
  datasource:
    url: jdbc:mysql://localhost:3306/sc
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8102                    # 指定该Eureka实例的端口
security:
  sessions: stateless
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@discovery:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true

#db
