---
spring:
  profiles: discovery1                                 # 指定profile=discovery1
server:
  port: 8761
eureka:
  instance:
    hostname: discovery1                               # 指定当profile=discovery1时，主机名
  client:
    serviceUrl:
      defaultZone: http://discovery2:8762/eureka/      # 将自己注册到discovery2这个Eureka上面去

security:
  basic:
    enabled: true
  user:
     name: root
     password: root
---
spring:
  profiles: discovery2
server:
  port: 8762
eureka:
  instance:
    hostname: discovery2
  client:
    serviceUrl:
      defaultZone: http://discovery1:8761/eureka/

security:
  basic:
    enabled: true
  user:
     name: root
     password: root