server:
  port: 9998                    # 指定该Eureka实例的端口

spring:
  application:
    name: plana-business-services
  datasource:
      url: jdbc:mysql://localhost:3306/plana
      username: root
      password: 123456
      type: org.mariadb.jdbc.MySQLDataSource
  rabbitmq:
      host: xyl
      username: guest
      password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@discovery:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true

scaff:
  mongo:
    host: 127.0.0.1
    database: plana
    auth: false
    maxWaitTime: 5000
    connectionTimeout: 5000
    connectionsPerHost: 5000
    threadsAllowedToBlockForConnectionMultiplier: 5000
